services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "402:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
      TZ: Europe/Berlin
      # TZ: Asia/Kolkata
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "405:3000"
    environment:
      TZ: Europe/Berlin
      # TZ: Asia/Kolkata
    volumes:
      - grafana-storage:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    ports:
      - "419:80"
    environment:
      TZ: Europe/Berlin
      # TZ: Asia/Kolkata
    volumes:
      - heimdall-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "426:9000"
    environment:
      TZ: Europe/Berlin
      # TZ: Asia/Kolkata
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  uptimekuma:
    image: louislam/uptime-kuma
    container_name: uptimekuma
    ports:
      - "439:3001"
    environment:
      TZ: Europe/Berlin
      # TZ: Asia/Kolkata
    volumes:
      - uptimekuma-data:/app/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      TZ: Europe/Berlin
      # TZ: Asia/Kolkata
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  openspeedtest:
    image: openspeedtest/latest
    container_name: openspeedtest
    ports:
      - "445:3000"
    environment:
      TZ: Europe/Berlin
      # TZ: Asia/Kolkata
    restart: unless-stopped

  mariadb-passbolt:
    image: mariadb:10.5
    container_name: mariadb-passbolt
    environment:
      MYSQL_ROOT_PASSWORD: ransha1
      MYSQL_DATABASE: passbolt
      MYSQL_USER: passbolt
      MYSQL_PASSWORD: ransha2
    volumes:
      - mariadb-passbolt-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  passbolt:
    image: passbolt/passbolt:latest
    container_name: passbolt
    depends_on:
      - mariadb-passbolt
    ports:
      - "8082:80"
    environment:
      DATASOURCES_DEFAULT_HOST: mariadb-passbolt
      DATASOURCES_DEFAULT_USERNAME: passbolt
      DATASOURCES_DEFAULT_PASSWORD: passbolt_password
      DATASOURCES_DEFAULT_DATABASE: passbolt
      APP_FULL_BASE_URL: http://mgn-m-4:8082
      TZ: Europe/Berlin
      # TZ: Asia/Kolkata
    volumes:
      - passbolt-data:/var/www/passbolt
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

volumes:
  pgadmin-data:
  grafana-storage:
  heimdall-config:
  portainer-data:
  uptimekuma-data:
  npm-data:
  npm-letsencrypt:
  mariadb-passbolt-data:
  passbolt-data:
